config/routes.rb
EcommerceAppChennaiocc::Application.routes.draw do
  devise_for :users

  resources :users

  resources :products

  get "products/payment/:id" => "products#payment"

  match "payment_receipt" => "products#payment_receipt"

  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :stripe_customer_token
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def payment
    @selected_product = Product.find(params[:id])
  end

  def payment_receipt

    # if params[:product][:stripe_customer_token] != nil
    #   customer =  Stripe::Charge.create(:amount => amount_in_cents, :currency => "usd", 
    #     :description => "product name", :card => params[:product][:stripe_customer_token])
      
    #   @product.stripe_customer_token = customer.id
    # end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce App Chennai OCC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= javascript_include_tag "https://js.stripe.com/v1/", "payment" %>
  <%= tag :meta, :name=>"stripe-key", :content=> STRIPE_PUBLIC_KEY %>

  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
   <div class="row">
    <div class="span9">
    	<% if notice %>
      <div class="alert alert-info"><%= notice %></div>
      <% end %>
      <% if alert %>
      <div class="alert alert-error"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
    <div class="span3">
      <h2>RoR at Chennai OCC</h2>
      <p><strong>Presented by:</strong> <br />
        <br />
        @iMagesh <br />
        @SpritleSoftware
      </p>        
    </div>
  </div>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table class = "table table-bordered">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/payment.html.erb
<h1>
	Make payment
</h2>

<%= form_for(@selected_product, :url=> payment_receipt_path, :html => {:id=> "new_payment"}) do |f| %>

<%= f.hidden_field :stripe_customer_token %>

<p>
	<b>Credit Card Number:</b>
	<%= text_field_tag :card_number, nil, :name => nil %>
</p>

<p>
	<b>Expiration:</b>
	<%= select_month nil, {:add_month_numbers => true}, {:name => nil, :id => "card_month" } %>
	<%= select_year nil, {:start_year => Date.today.year, :end_year => Date.today.year+5}, {:name => nil, :id => "card_year", :class => "year-input"} %>  
</p>

<p>
	<b>Security Code:</b>
	<%= text_field_tag :card_code, nil, :name => nil %>
</p>

<p>
	<%= f.submit "Purchase", :disable_with => "Please wait...", :class => "btn btn-small btn-primary" ,:id=>"purchase_id", 
	:style => "float: left; margin-right: 1%;" %>
	<span class="alert alert-error" id="stripe_error" style="float: left; display:none;">Processing!</span>            
</p>       

<% end %>

app/views/products/payment_receipt.html.erb
<h1>Thanks for your purchase</h1>

<%= link_to 'All products', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @product.name %>
</h2>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <a href="/products/payment/<%= @product.id %>" class="btn btn-mini btn-primary">Buy Now</a>
</p>

<%= link_to 'All products', products_path %>